version: '3.8'

services:
  schedparse:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: schedparse_app
    ports:
      - "3434:5000"
    volumes:
      - ./app.py:/app/app.py
      - ./requirements.txt:/app/requirements.txt
    restart: unless-stopped
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/api/cacheStats"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
    # Install curl and dependencies for healthcheck
    command: >
      bash -c "apt-get update && apt-get install -y curl && 
      pip install --no-cache-dir -r requirements.txt && 
      python app.py"

  redis:
    image: redis:7-alpine
    container_name: schedparse_redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: unless-stopped
    command: redis-server --save 60 1 --loglevel warning

volumes:
  redis-data: